"""cand rec id added

Revision ID: 01a7ccbcb98b
Revises: c07e6e198a47
Create Date: 2026-02-20 11:29:25.238733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01a7ccbcb98b'
down_revision: Union[str, None] = 'c07e6e198a47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_profiles', sa.Column('recruiter_id', sa.String(length=36), nullable=False))
    op.create_index(op.f('ix_candidate_profiles_recruiter_id'), 'candidate_profiles', ['recruiter_id'], unique=False)
    op.create_foreign_key(None, 'candidate_profiles', 'users', ['recruiter_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'candidate_profiles', type_='foreignkey')
    op.drop_index(op.f('ix_candidate_profiles_recruiter_id'), table_name='candidate_profiles')
    op.drop_column('candidate_profiles', 'recruiter_id')
    # ### end Alembic commands ###
