"""job interview connected

Revision ID: 08d25f3777b6
Revises: a0b66d8fe428
Create Date: 2026-03-31 21:00:34.885953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '08d25f3777b6'
down_revision: Union[str, None] = 'a0b66d8fe428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('RECOVER_YOUR_DATA_info')
    op.add_column('interviews', sa.Column('job_id', sa.String(length=36), nullable=False))
    op.create_index(op.f('ix_interviews_job_id'), 'interviews', ['job_id'], unique=False)
    op.create_foreign_key(None, 'interviews', 'job_descriptions', ['job_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interviews', type_='foreignkey')
    op.drop_index(op.f('ix_interviews_job_id'), table_name='interviews')
    op.drop_column('interviews', 'job_id')
    op.create_table('RECOVER_YOUR_DATA_info',
    sa.Column('READ_ME', mysql.TEXT(), nullable=True),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
