"""add about_company to job_descriptions

Revision ID: 0db3d998b75a
Revises: d236c5c5d626
Create Date: 2026-03-09 21:47:36.100677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0db3d998b75a'
down_revision: Union[str, None] = 'd236c5c5d626'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_descriptions', sa.Column('about_company', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_descriptions', 'about_company')
    # ### end Alembic commands ###
