"""candidate status added

Revision ID: 1e7e25d41374
Revises: fb9dbfc49d64
Create Date: 2026-02-24 16:37:21.333674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e7e25d41374'
down_revision: Union[str, None] = 'fb9dbfc49d64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_profiles', sa.Column('status', sa.Enum('SOURCED', 'MATCHED', 'SCREENING', 'INTERVIEW', 'OFFER', 'HIRED', name='candidatestatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_profiles', 'status')
    # ### end Alembic commands ###

