"""certificate null removed

Revision ID: 337820bcbfae
Revises: 492932b7001e
Create Date: 2026-02-13 14:55:19.935797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '337820bcbfae'
down_revision: Union[str, None] = '492932b7001e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('certifications', 'certification_description',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('certifications', 'issue_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('certifications', 'status',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('ACTIVE', 'EXPIRED', 'REVOKED', name='certificationstatus'),
               existing_nullable=True)
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.alter_column('certifications', 'status',
               existing_type=sa.Enum('ACTIVE', 'EXPIRED', 'REVOKED', name='certificationstatus'),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('certifications', 'issue_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('certifications', 'certification_description',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
