"""certification added

Revision ID: 492932b7001e
Revises: e35ea97c7e54
Create Date: 2026-02-12 12:28:22.418583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '492932b7001e'
down_revision: Union[str, None] = 'e35ea97c7e54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certifications', sa.Column('certification_description', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('certifications', 'certification_description')
    # ### end Alembic commands ###
