"""interview edited

Revision ID: 53beffcdf394
Revises: fa69472ff9d3
Create Date: 2026-02-18 12:16:35.829516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53beffcdf394'
down_revision: Union[str, None] = 'fa69472ff9d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('scores', sa.Integer(), nullable=True))
    op.add_column('interviews', sa.Column('ai_summary', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'ai_summary')
    op.drop_column('interviews', 'scores')
    # ### end Alembic commands ###
