"""interview bugs fixed 2

Revision ID: 65a8f8a62d8a
Revises: 1a9c83074d79
Create Date: 2026-03-15 21:23:34.315965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '65a8f8a62d8a'
down_revision: Union[str, None] = '1a9c83074d79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('interview_recordings_ibfk_1'), 'interview_recordings', type_='foreignkey')
    op.drop_index(op.f('ix_interview_recordings_interview_id'), table_name='interview_recordings')
    op.create_index(op.f('ix_interview_recordings_section_id'), 'interview_recordings', ['section_id'], unique=False)
    op.create_unique_constraint(None, 'interview_recordings', ['section_id', 'question_index'])
    op.create_foreign_key(None, 'interview_recordings', 'interview_section_configs', ['section_id'], ['id'], ondelete='CASCADE')
    op.drop_column('interview_recordings', 'interview_id')
    op.add_column('interview_section_configs', sa.Column('seconds_per_question', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_section_configs', 'seconds_per_question')
    op.add_column('interview_recordings', sa.Column('interview_id', mysql.VARCHAR(length=36), nullable=False))
    op.drop_constraint(None, 'interview_recordings', type_='foreignkey')
    op.create_foreign_key(op.f('interview_recordings_ibfk_1'), 'interview_recordings', 'interviews', ['interview_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'interview_recordings', type_='unique')
    op.drop_index(op.f('ix_interview_recordings_section_id'), table_name='interview_recordings')
    op.create_index(op.f('ix_interview_recordings_interview_id'), 'interview_recordings', ['interview_id'], unique=False)
    # ### end Alembic commands ###
