"""reset and verify added

Revision ID: 71f0c80c0f77
Revises: 01a7ccbcb98b
Create Date: 2026-02-20 20:51:36.762723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71f0c80c0f77'
down_revision: Union[str, None] = '01a7ccbcb98b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'candidate_profiles', 'users', ['recruiter_id'], ['id'])
    op.add_column('users', sa.Column('is_email_verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verified_at')
    op.drop_column('users', 'is_email_verified')
    op.drop_constraint(None, 'candidate_profiles', type_='foreignkey')
    # ### end Alembic commands ###
