"""ai interview config added

Revision ID: 88b7331d87ef
Revises: 0db3d998b75a
Create Date: 2026-03-13 19:10:53.876344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '88b7331d87ef'
down_revision: Union[str, None] = '0db3d998b75a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_section_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('interview_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('no_of_questions', sa.Integer(), nullable=False),
    sa.Column('custom_questions', sa.JSON(), nullable=True),
    sa.Column('is_follow_up', sa.Boolean(), nullable=False),
    sa.Column('questions', sa.JSON(), nullable=True),
    sa.Column('qa', sa.JSON(), nullable=True),
    sa.Column('ai_score', sa.Integer(), nullable=True),
    sa.Column('ai_summary', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_section_configs_interview_id'), 'interview_section_configs', ['interview_id'], unique=False)
    op.add_column('interviews', sa.Column('status', sa.Enum('NOT_STARTED', 'ONGOING', 'COMPLETED', 'MALPRACTICE', name='interviewstatus'), nullable=False))
    op.drop_column('interviews', 'qa')
    op.drop_column('interviews', 'scores')
    op.drop_column('interviews', 'ai_summary')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('ai_summary', mysql.JSON(), nullable=True))
    op.add_column('interviews', sa.Column('scores', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('interviews', sa.Column('qa', mysql.JSON(), nullable=True))
    op.drop_column('interviews', 'status')
    op.drop_index(op.f('ix_interview_section_configs_interview_id'), table_name='interview_section_configs')
    op.drop_table('interview_section_configs')
    # ### end Alembic commands ###
