"""index added for interview sections

Revision ID: 8f75696e48c6
Revises: ed2ed1a2ef49
Create Date: 2026-04-06 20:28:31.268778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f75696e48c6'
down_revision: Union[str, None] = 'ed2ed1a2ef49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_section_configs', sa.Column('order_index', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_section_configs', 'order_index')
    # ### end Alembic commands ###
