"""qa added interview edited

Revision ID: c07e6e198a47
Revises: 53beffcdf394
Create Date: 2026-02-19 16:38:48.485021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c07e6e198a47'
down_revision: Union[str, None] = '53beffcdf394'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('qa', sa.JSON(), nullable=True))
    op.alter_column('interviews', 'ai_summary',
               existing_type=mysql.VARCHAR(length=2000),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interviews', 'ai_summary',
               existing_type=sa.JSON(),
               type_=mysql.VARCHAR(length=2000),
               existing_nullable=True)
    op.drop_column('interviews', 'qa')
    # ### end Alembic commands ###
