"""otp table added

Revision ID: c442e4582931
Revises: 149c7387a349
Create Date: 2026-03-05 16:21:12.804654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c442e4582931'
down_revision: Union[str, None] = '149c7387a349'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otps', sa.Column('resend_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('otps', 'resend_count')
    # ### end Alembic commands ###
