"""assessment json changed

Revision ID: ced5e0e8b4aa
Revises: dd70bc130b53
Create Date: 2026-04-02 13:11:03.304465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ced5e0e8b4aa'
down_revision: Union[str, None] = 'dd70bc130b53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'interviews', 'job_descriptions', ['job_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interviews', type_='foreignkey')
    # ### end Alembic commands ###
