"""otp changed

Revision ID: d236c5c5d626
Revises: c442e4582931
Create Date: 2026-03-06 15:56:52.319532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd236c5c5d626'
down_revision: Union[str, None] = 'c442e4582931'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('otps', 'otp',
               existing_type=mysql.VARCHAR(length=6),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('otps', 'otp',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=6),
               existing_nullable=False)
    # ### end Alembic commands ###
