"""certification added

Revision ID: e35ea97c7e54
Revises: 8aff7431fc5d
Create Date: 2026-02-12 11:37:27.790361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e35ea97c7e54'
down_revision: Union[str, None] = '8aff7431fc5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('candidate_profile_id', sa.String(length=36), nullable=False),
    sa.Column('certification_name', sa.String(length=255), nullable=False),
    sa.Column('issuing_body', sa.String(length=255), nullable=True),
    sa.Column('credential_id', sa.String(length=100), nullable=True),
    sa.Column('verification_url', sa.String(length=500), nullable=True),
    sa.Column('issue_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'REVOKED', name='certificationstatus'), nullable=True),
    sa.Column('certificate_file', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certifications_candidate_profile_id'), 'certifications', ['candidate_profile_id'], unique=False)
    op.create_index(op.f('ix_certifications_id'), 'certifications', ['id'], unique=False)
    op.drop_index(op.f('uq_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('uq_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_certifications_id'), table_name='certifications')
    op.drop_index(op.f('ix_certifications_candidate_profile_id'), table_name='certifications')
    op.drop_table('certifications')
    # ### end Alembic commands ###
