"""assessments removed

Revision ID: ed2ed1a2ef49
Revises: ced5e0e8b4aa
Create Date: 2026-04-06 16:10:02.718608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ed2ed1a2ef49'
down_revision: Union[str, None] = 'ced5e0e8b4aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessments_assessment_type'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_candidate_email'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_candidate_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_recruiter_id'), table_name='assessments')
    op.drop_table('assessments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessments',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('recruiter_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('candidate_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('candidate_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('candidate_email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('assessment_type', mysql.ENUM('TECHNICAL', 'APTITUDE', 'LOGICAL', 'PSYCHOMETRIC', 'CODING'), nullable=False),
    sa.Column('data', mysql.JSON(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('time', mysql.TIME(), nullable=False),
    sa.Column('score', mysql.FLOAT(), nullable=True),
    sa.Column('ai_summary', mysql.JSON(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['users.id'], name=op.f('assessments_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recruiter_id'], ['users.id'], name=op.f('assessments_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_assessments_recruiter_id'), 'assessments', ['recruiter_id'], unique=False)
    op.create_index(op.f('ix_assessments_id'), 'assessments', ['id'], unique=False)
    op.create_index(op.f('ix_assessments_candidate_id'), 'assessments', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_assessments_candidate_email'), 'assessments', ['candidate_email'], unique=False)
    op.create_index(op.f('ix_assessments_assessment_type'), 'assessments', ['assessment_type'], unique=False)
    # ### end Alembic commands ###
