"""interview s3 added

Revision ID: f3a3632bdd38
Revises: 71f0c80c0f77
Create Date: 2026-02-23 14:03:12.514903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3a3632bdd38'
down_revision: Union[str, None] = '71f0c80c0f77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('s3_object_key', sa.String(length=512), nullable=True))
    op.add_column('interviews', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'completed_at')
    op.drop_column('interviews', 's3_object_key')
    # ### end Alembic commands ###
