"""interview recordings recreated

Revision ID: f4ce555e26b8
Revises: 65a8f8a62d8a
Create Date: 2026-03-15 21:34:43.324083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4ce555e26b8'
down_revision: Union[str, None] = '65a8f8a62d8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_recordings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('section_id', sa.String(length=36), nullable=False),
    sa.Column('question_index', sa.Integer(), nullable=False),
    sa.Column('s3_object_key', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['interview_section_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id', 'question_index')
    )
    op.create_index(op.f('ix_interview_recordings_section_id'), 'interview_recordings', ['section_id'], unique=False)
    op.add_column('interview_section_configs', sa.Column('seconds_per_question', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_section_configs', 'seconds_per_question')
    op.drop_index(op.f('ix_interview_recordings_section_id'), table_name='interview_recordings')
    op.drop_table('interview_recordings')
    # ### end Alembic commands ###
