"""dummy revision

Revision ID: fa69472ff9d3
Revises: 337820bcbfae
Create Date: 2026-02-16 20:03:31.486574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa69472ff9d3'
down_revision: Union[str, None] = '337820bcbfae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_users_email'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###
