"""interview s3 table updated

Revision ID: fb9dbfc49d64
Revises: f3a3632bdd38
Create Date: 2026-02-23 14:49:56.278909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fb9dbfc49d64'
down_revision: Union[str, None] = 'f3a3632bdd38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_recordings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('interview_id', sa.String(length=36), nullable=False),
    sa.Column('question_index', sa.Integer(), nullable=False),
    sa.Column('s3_object_key', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('interview_id', 'question_index')
    )
    op.create_index(op.f('ix_interview_recordings_interview_id'), 'interview_recordings', ['interview_id'], unique=False)
    op.drop_column('interviews', 's3_object_key')
    op.drop_column('interviews', 'completed_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('completed_at', mysql.DATETIME(), nullable=True))
    op.add_column('interviews', sa.Column('s3_object_key', mysql.VARCHAR(length=512), nullable=True))
    op.drop_index(op.f('ix_interview_recordings_interview_id'), table_name='interview_recordings')
    op.drop_table('interview_recordings')
    # ### end Alembic commands ###
